### ISSUE TITLE
Calculating absolute binding free energy for membrane proteins 

### ISSUE THREAD

**Issue by amara86** [GHeinzelmann/BAT.py#37] opened 2024-08-14 01:43 UTC
Hi
I have membrane protein complex with small molecules. I have already embedded the complex into the membrane using CharmmGUI, just inquiring if BAT.py can work with membrane proteins? and does it require any specific modifications?
Regards,
Amara

**Comment by GHeinzelmann** [comment] 2024-08-15 15:28
Duplicate of another issue, closing this and responding to the other one.

**Closed as completed by GHeinzelmann** 2024-08-15 15:28 UTC
