### ISSUE TITLE
Possible unreferenced variable

### ISSUE THREAD

**Issue by jaketanderson** [GHeinzelmann/BAT.py#27] opened 2022-09-05 06:17 UTC
When running `box_volume()`, I ran into trouble where apparently there was no "Density" anywhere in `tmp.log`, meaning the variable `ratio` went unassigned and threw an UnboundLocalError. Maybe `ratio` should have a default value (of 1)? Or perhaps there should never arise a situation where `tmp.log` doesn't have a "Density"-containing line, and my program is broken in some way...

https://github.com/GHeinzelmann/BAT.py/blob/c977da77fe6291a73643d26716956de887bf815d/BAT/lib/scripts.py#L64-L81

**Comment by jaketanderson** [comment] 2022-09-05 06:25
Hmm, manually entering a value for `ratio` gave me the same issue but with `x_axis`. So it looks like tleap is failing in some way. I took a look at `tmp.log` and this fatal error stopped things:

> Log file: ./leap.log
Loading parameters: /data/jta002/anaconda3/envs/bat/dat/leap/parm/gaff.dat
Reading title:
AMBER General Force Field for organic molecules (Version 1.81, May 2017)
Loading parameters: ./dum.frcmod
Reading force field modification type file (frcmod)
Reading title:
Parameters for a "Lead-like" Dummy Atom
Loading Mol2 file: ./dum.mol2
Reading MOLECULE named DUM
Loading parameters: ./lig.frcmod
Reading force field modification type file (frcmod)
Reading title:
Remark line goes here
Loading Mol2 file: ./lig.mol2
Reading MOLECULE named LIG
Loading PDB file: ./build.pdb
  Added missing heavy atom: .R<CMET 110>.A<OXT 18>

>/data/jta002/anaconda3/envs/bat/bin/teLeap: Fatal Error!
Atom .R<LIG 1>.A<C9 13> has force field coordination 4
       but only 3 bonded neighbors.
       The cause may be an incorrect atom type, and
       the effect may be a crash very soon (if running interactively).

**Comment by jaketanderson** [comment] 2022-09-05 07:02
Here is the ligand from `equil/pose0/build.pdb` that I think has the offending atom:

> TER
ATOM    894 C    LIG   111       3.837  -0.049  11.528  0.00  0.00
ATOM    895 C1   LIG   111       3.945   1.305  11.878  0.00  0.00
ATOM    896 C2   LIG   111       4.744   2.159  11.120  0.00  0.00
ATOM    897 O    LIG   111       4.840   3.374  11.447  0.00  0.00
ATOM    898 N    LIG   111       5.422   1.670  10.040  0.00  0.00
ATOM    899 C3   LIG   111       6.276   2.542   9.234  0.00  0.00
ATOM    900 N1   LIG   111       5.304   0.387   9.692  0.00  0.00
ATOM    901 C4   LIG   111       4.531  -0.494  10.382  0.00  0.00
ATOM    902 C5   LIG   111       4.433  -1.879   9.872  0.00  0.00
ATOM    903 C6   LIG   111       5.336  -2.855  10.325  0.00  0.00
ATOM    904 C7   LIG   111       5.273  -4.159   9.824  0.00  0.00
ATOM    905 C8   LIG   111       4.321  -4.494   8.858  0.00  0.00
**ATOM    906 C9   LIG   111       3.434  -3.523   8.386  0.00  0.00**
ATOM    907 C10  LIG   111       3.492  -2.218   8.884  0.00  0.00
ATOM    908 N2   LIG   111       3.093  -0.969  12.354  0.00  0.00
ATOM    909 C11  LIG   111       1.949  -0.572  13.170  0.00  0.00
TER
END

For reference, I'm running `python BAT.py -i input-sdr-openmm.in -s equil` on a local cluster. I had success performing the same command on my Ubuntu 22.04 PC, but for some reason there are issues doing it on the new machine. Running `python BAT.py -i input-dd-openmm.in -s equil` gave the same error, but running `python BAT.py -i input-dd-long.in -s equil` (just to see setup; I am not using pmemd) gave an error:
> Creating box...
Problem solvating system, check your input file and the tleap log file

Anyone have thoughts on what might be going on here?

**Comment by GHeinzelmann** [comment] 2022-09-07 17:35
Hi Jake. It indeed seems that the problem is with the parameters read by tleap, which might have to do with the protonation and and/or the antechamber atom type assignment. When using the openbabel and Ambertools versions from the tutorial I don't run into this problem, but apparently something is happening differently in your new machine. The fact that it runs normally in your machine and not in the cluster seems to confirm this assessment of the situation. 

I would suggest checking the ligand protonation after the openbabel command and see if anything looks funny, such as a carbon atom assigned as sp3 type with only 3 bonded atoms. Note that you can also run the protonation and parameter generation part separately, and include the generated .mol2 and .frcmod files inside an equil/ff folder you would create before running BAT. That way BAT will skip the parameter generation and instead use the parameters you provided. 

I would appreciate if you let me know what the problem is after you find it, so I can avoid it for other users. Thanks!

**Comment by jaketanderson** [comment] 2022-09-08 23:32
I actually was experiencing weird problems with my anaconda environments, and I ended up deleting all of my anaconda data and doing a fresh install. I was pleasantly surprised when this also fixed the issue I was seeing in BAT.py. So fortunately for me the issue is now resolved. Unfortunately for others, I don't think this issue is reproducible and I'm not sure if it can be fixed with less drastic measures.

If anyone else has this issue and nothing seems to solve it, I can recommend removing the particular conda environment and starting a new one. And if that still doesn't work, the issue might be that conda is having weird issues itself and a conda reinstall could be necessary.

I'll link the conda environment that I ended up using in case it's useful. The env has `ambertools=22.0`, `openmm=7.7.0`, `openmmtools=0.21.5`, `cudatoolkit=11.4.2`, and `openbabel=2.4.1`. [Here's the yml](https://pastebin.com/Dve30Huj).

**Comment by GHeinzelmann** [comment] 2022-09-09 00:28
Great that it worked, and thanks for the detailed information. I have only used conda for the OpenMM simulations, so I could not have known of this potential issue with the parameter generation. Thanks again for the help! Closing issue.

**Closed as completed** 2022-09-09 00:29 UTC
